substitutions:
  _SERVICE_NAME: 'hglowe-www'
  _REGION: 'us-central1'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE_NAME}'
      - '-f'
      - './Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE_NAME}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/${_SERVICE_NAME}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8080'


timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
