substitutions:
  _SERVICE_NAME: 'hglowe-www'
  _REGION: 'us-central1'
  _IMAGE: 'us-central1-docker.pkg.dev/$PROJECT_ID/containers/hglowe-www'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '80'

images:
  - '${_IMAGE}'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
